### PR TITLE
feat: Add initial support for OpenTelekomCloud's CCE

### PR DESCRIPTION
**Pull request by chornberger-c2c**

### CODE REVIEW

**Comment by raphink** [comment]
@chornberger-c2c What is the status of this PR?

**Comment by chornberger-c2c** [comment]
@raphink 

There is one open issue: 

creation of a load balancer in front of the ingress controller.
It is to be addressed until 2021-08-09.

Spawning the cluster and pulling applications via ArgoCD works.

**Comment by chornberger-c2c** [comment]
@raphink 

There is one open issue: 

creation of a load balancer in front of the ingress controller.
It is to be addressed until 2021-08-09.

Spawning the cluster and pulling applications via ArgoCD works.

**Review by mcanevet — CHANGES_REQUESTED** [review]

**Comment by mcanevet** [comment]
superseded by #756

**Pull request closed without merging**
