### PR TITLE
feat(sks): make NLB creation optional

### PR DESCRIPTION
**Pull request by ckaenzig**
This allows using the devops stack with an existing or externally managed
load balancer.

### CODE REVIEW

**Review by raphink — CHANGES_REQUESTED** [review]
LGTM, but I wonder if the variable could be called `enabled_lb` or `enable_loadbalancer` so that we can implement it the same way on other distributions as a standard.

**Comment by ckaenzig** [comment]
I found that modules often user `create_*` variables names for this (ex. https://github.com/terraform-aws-modules/terraform-aws-alb#conditional-creation). In this case, `create_lb` would indeed be more generic. I will modify the PR to change that.

**Comment by ckaenzig** [comment]
Actually I just saw that `create_lb` is _less_ consistent with the variables we have in the eks/aws/ module, namely `create_public_nlb` and `create_private_nlb`.

**Comment by ckaenzig** [comment]
Closing this PR because it's not needed in any current project anymore, and not relevant to the next modular version.

**Pull request closed without merging**
