### PR TITLE
feat: enable support for network policy in azure

### PR DESCRIPTION
**Pull request by modridi**

### CODE REVIEW

**Comment by mcanevet** [comment]
- Is it available in v4.7.0 of the Azure/AKS module.
- Maybe we should only expose the parameter and not change de default yet, because it will force replacement of the cluster.

**Review by mcanevet — CHANGES_REQUESTED** [review]
Changing the default behavior will enforce cluster recreation on upgrade.
Maybe we should expose the attribute en set it either to `azure` as default (will allow to override to `null`) or to `null` as default (will allow to override to `azure`).

**Comment by modridi** [comment]
> Changing the default behavior will enforce cluster recreation on upgrade.
> Maybe we should expose the attribute en set it either to `azure` as default (will allow to override to `null`) or to `null` as default (will allow to override to `azure`).

Then it's up to the module caller to set the value ?

**Comment by modridi** [comment]
>     * Is it available in v4.7.0 of the Azure/AKS module.
> 
>     * Maybe we should only expose the parameter and not change de default yet, because it will force replacement of the cluster.

Yes, it is supported in 4.7.0**.**

**Review by mcanevet — APPROVED** [review]

**Pull request merged**
