### PR TITLE
feat(kind): add experimental support for KIND

### PR DESCRIPTION
**Pull request by mcanevet**
Why? Because kind supports Podman

### CODE REVIEW

**Review by raphink — DISMISSED** [review]
LGTM, just missing docs

**Comment by mcanevet** [comment]
and we should also run tests in github workflow

**Comment by raphink** [comment]
OIDC validation fails because `127.0.0.1` cannot be reached from within the containers. We need to use one of the VM's ip addresses instead to build the nip.io domain.

**Review by raphink — APPROVED** [review]
Let's approve this and I'll figure out the issue later

**Pull request merged**
