### PR TITLE
Allowing extra apps chart to be located in the root

### PR DESCRIPTION
**Pull request by pburgisser**
Allowing extra apps chart to be located in the root and to not specify a path

### CODE REVIEW

**Comment by mcanevet** [comment]
Hmmm, I'm not sure to understand the purpose of this. You already can set `./` as path.

**Comment by pburgisser** [comment]
@mcanevet To avoid specifying it :-)

**Comment by mcanevet** [comment]
OK, I'm not sure it's a good idea to have such default. @raphink what do you think?
Anyway, this part will probably be changed with ArgoCD 2.x and the arrival of the ApplicationSets.

**Comment by pburgisser** [comment]
As an alternative, we could omit the path when not specified

**Comment by mcanevet** [comment]
Actually I'd like to remove this parameter in favor of #568

**Comment by pburgisser** [comment]
@mcanevet It makes more sens then.
I'll close this PR.

**Pull request closed without merging**
