### PR TITLE
Adding support of Thanos when a bucket is provided

### PR DESCRIPTION
**Pull request by pburgisser**
This PR implements:

- Thanos Store Gateway to access the data stored in a object storage
- Thanos Query to access both the Storage gateway and the existing prometheus
- Thanos Query Frontend: Frontend for querier 
- Thanos Bucket Web to visualize the blocks on the Object Storage
- Automatically configures Grafana to access the querier

Missing: The bitnami chart doesn't offer the possibility to add a sidecar containers for the frontend, so there is no OAuth integration

### CODE REVIEW

**Comment by mcanevet** [comment]
@pburgisser I guess you should rebase now that your openshift4/aws has been merged.

**Review by mcanevet — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by mcanevet** [comment]
@cryptobioz I have no experience at all in Thanos. As you have some, I think it would be a good idea that you review this PR.

**Comment by pburgisser** [comment]
FYI, I'm working on a PR on the bitnami chart to integrate more containers so we can implement the front oauthproxy.
I'll probably make a second PR after this one to enhance it.

**Comment by pburgisser** [comment]
@cryptobioz May I ask you for a review? please :)

**Review by cryptobioz — DISMISSED** [review]
LGTM

**Comment by pburgisser** [comment]
@mcanevet May I merge? I've just rebased

**Review by mcanevet — APPROVED** [review]
I think it can't break anything what exists, so +1 to merge this.

**Pull request merged**
