### PR TITLE
feat(sks): expose k8s cluster credentials in outputs

### PR DESCRIPTION
**Pull request by ckaenzig**

### CODE REVIEW

**Review by raphink — COMMENTED** [review]
There is already a standard `kubeconfig` output for all distributions. Do you really need these outputs separately?

**Comment by ckaenzig** [comment]
Yes, I need these separate outputs to feed to the kubernetes provider in the root module.

**Comment by raphink** [comment]
For Helm, you could drop the file locally and then use it with `config_paths`, but that's not very elegant.

If we're going to add these outputs, we might as well add them as standards in addition to `kubeconfig` in `modules/variables.tf`.

**Comment by ckaenzig** [comment]
Closing this PR because it's not needed in any current project anymore, and not relevant to the next modular version.

**Pull request closed without merging**
