### PR TITLE
fix(sks): don't try to output keycloak password when disabled

### PR DESCRIPTION
**Pull request by ckaenzig**

### CODE REVIEW

**Comment by mcanevet** [comment]
I'm wondering if there's a better way to figure out whether keycloak is enabled or not...

**Comment by mcanevet** [comment]
It would maybe be more robust to use yamldecode on the values passed to the app of apps and look at `apps.keycloak.enabled`

**Comment by mcanevet** [comment]
@ckaenzig I'll close this PR and remove the branch in this repo. Please open it again from your fork (/cc @vquiby )

**Comment by ckaenzig** [comment]
@mcanevet The values in question are only available as a list of 3 yaml strings which are then merged by helm. It doesn't look like terraform could somehow do the same merge with the same strategy to then extract the `appls.keycload.enabled` value.

**Comment by mcanevet** [comment]
@ckaenzig indeed. Doesn't the datasource lookup completely fails when keycloak is disabled?

**Comment by ckaenzig** [comment]
No, the datasource doesn't throw any error when the secret doesn't exist. It's `data` attribute is just set to `null`.

**Pull request closed without merging**
