### PR TITLE
Upgrade k3s to v1.20.x

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by raphink** [comment]
LGTM. The helm-docs need to be regenerated (see Makefile)

**Comment by mcanevet** [comment]
@raphink when I run `make` it says `make: Nothing to be done for 'refs'.`

**Comment by raphink** [comment]
Ah yes, run `make clean_refs` first

**Comment by mcanevet** [comment]
@raphink Voilà!

**Review by raphink — APPROVED** [review]

**Comment by raphink** [comment]
👍

**Pull request merged**
